#!/bin/dash
# Ver.iwm20250116
# 以下の使用を想定
#   Openbox + tint2
#   $HOME/.config/openbox/autostart から起動

# 複数起動禁止
#xreadonly ThisPS=$(ps --no-headers -o pid,cmd -C $(basename "$0"))
#x[ $(echo "${ThisPS}" | wc -l) -ge 2 ] && exit

iwm_SubPkgInstall "yad"

readonly ObFile=$(
cat <<-EOD
	rc.xml
	menu.xml
	autostart
EOD
)

ObArgv=""

IFS="
"
for _1 in $(echo "${ObFile}")
do
	ObArgv="${ObArgv} $HOME/.config/openbox/${_1}"
done

readonly Menu=$(
cat <<-EOD
	Update ! x-terminal-emulator -e iwm_update ! synaptic
	Synaptic ! synaptic-pkexec ! synaptic
	obconf ! obconf ! obconf
	openbox --restart ! openbox --restart ! gtk-refresh
	Edit Openbox ! mousepad ${ObArgv} ! mousepad
	tint2conf ! tint2conf ! tint2conf
	Conky On/Off ! iwm_conky_OnOff ! conky
	Wallpaper ! iwm_feh ! feh
	Volume ! iwm_volume ! stock_volume-med
EOD
)

# Label ! Command ! Icon |
readonly MenuArgv=$(
	echo "${Menu}" \
	| sed -E 's/^[ ]+//g' \
	| sed -E 's/[ ]*![ ]*/!/g' \
	| sed -E 's/[ ]+$//g' \
	| tr '\n' '|' \
)

# 通知エリアに常駐
yad	--notification --image="gtk-execute" \
	--text="Openbox and other settings menus" \
	--command="iwm_openbox-shortcut-keys" \
	--menu="${MenuArgv}"
