#!/bin/dash
# Ver.iwm20241118

# 入力履歴消去
find "${HOME}" -name "*_history*" | xargs rm -rf

# su -
## iwm_sudo true

# 以下
# lsコマンドでは "Dir/File" のような表示ができないので  findコマンドを使用
Cmd="find /var/log 2>/dev/null"

# ６世代以上のログを削除
Gen="([6-9]|[1-9][0-9])"

# '.NUM.gz'（NUM>=6）で終わるとき
eval ${Cmd} | grep -E '\.${Gen}\.gz$' | sudo xargs rm -f

# '.log.NUM'（NUM>=6）で終わるとき
eval ${Cmd} | grep -E '\.log\.${Gen}$' | sudo xargs rm -f

# Shutdown
systemctl poweroff
