#!/bin/dash
# Ver.iwm20250102

iwm_SubPkgInstall "feh" "yad"

Title="壁紙変更"

#--------------------------------------------
# RtnSelectImage
#   $1 = 壁紙のファイル名 (例) "~/bg01.jpg"
#--------------------------------------------
RtnSelectImage()
{
	_fn="$1"

	[ -z "${_fn}" ] && _fn="$HOME"

	_rtn=$(
		yad --file \
			--filename="${_fn}" \
			--file-filter="画像 ファイル (*.jpg *.png *.gif) | *.jpg *.png *.gif" \
			--file-filter="すべてのファイル | *" \
			--add-preview --large-preview \
			--button="Cancel:1" --button="OK:0" \
			--title="${Title}" \
			--width="640" --borders="4" --center --on-top \
			2>/dev/null \
	)

	echo "${_rtn}"
}

readonly CbList="center|fill|scale|tile"

#------------------------------------
# RtnSelectBgStyle
#   $1 = 壁紙の配置方法 (例) "fill"
#------------------------------------
RtnSelectBgStyle()
{
	_1=""
	[ -n "$1" ] \
		&& _1="$1|${CbList}" \
		|| _1="${CbList}"

	_rtn=$(
		yad --form \
			--item-separator="|" \
			--separator="" \
			--field="配置":CB "${_1}" \
			--button="Cancel:1" --button="OK:0" \
			--title="${Title}" \
			--fixed --borders="4" --center --on-top \
	 		2>/dev/null \
	)

	echo "${_rtn}"
}

#-----------------------------------------
# RtnConfirm
#   $1 = 確認文言 (例) ""確定しますか ?"
#-----------------------------------------
RtnConfirm()
{
	yad --text "$1" \
		--button="Cancel:1" --button="OK:0" \
		--title="${Title}" \
		--fixed --borders="4" --center --on-top \
		2>/dev/null

	# OK=0, Cancel=1
	echo "$?"
}

#-------
# main
#-------
ImageFile=""
BgStyle=""
Repeat=""

while true
do
	ImageFile=$(RtnSelectImage "${ImageFile}")
	[ -z "${ImageFile}" ] && break

	BgStyle=$(RtnSelectBgStyle "${BgStyle}")
	if [ -n "${BgStyle}" ]
	then
		feh --bg-${BgStyle} ${ImageFile}
		[ $(RtnConfirm "確定しますか ?" "${Title}") = "0" ] && break
	fi
done
