#!/bin/dash
# Ver.iwm2024121

# 引数チェック
if [ $# -lt 2 ] || [ "${1}" = "--help" ] || [ "${1}" = "-h" ]
then
	bn=$(basename "${0}")
	echo "\033[38;2;255;255;255m\033[104m 検索したファイルのアクセス権を一括変更 \033[0m"
	echo "    \033[38;2;255;255;255m${bn} \033[38;2;255;150;150m[Dir] \033[38;2;150;150;255m[Regex] \033[38;2;0;150;255m[Chmod]"
	echo
	echo " \033[93m(例)"
	echo "    \033[38;2;255;255;255m${bn} \033[38;2;255;150;150m'./' \033[38;2;150;150;255m'\.(jpg|png)$' \033[38;2;0;150;255m644"
	echo "    \033[95mシングルクォーテーション ' で区切ること!!"
	echo "\033[0m"
	exit
fi

# $2 は拡張正規表現 -E 'STR' で扱う
readonly List=$( \
	find "$1" -type f \
	| grep -i -E $2 \
	| xargs -I {} ls {}
)

echo
echo "${List}" \
| xargs -I {} ls -l --time-style=long-iso {} \
| while IFS=" " read _1 _2 _3 _4 _5 _6 _7 _8
do
	echo "\033[92m${_1} \033[37m${_8}"
done

echo
echo "\033[92mアクセス権\033[0mを\033[96m$3\033[0mに一括変更"
echo "\033[95m実行しますか \033[45;97m Yes=1 \033[49m"
echo -n "\033[95m?\033[0m "

read _1

if [ "${_1}" = "1" ]
then
	echo "${List}" \
	| xargs -I {} chmod $3 {}

	echo

	echo "${List}" \
	| xargs -I {} ls -l --time-style=long-iso {} \
	| while IFS=" " read _1 _2 _3 _4 _5 _6 _7 _8
	do
		echo "\033[96m${_1} \033[37m${_8}"
	done
fi

echo "\033[0m"
