#!/bin/dash
# Ver.iwm20241221

iwm_SubPkgInstall "feh" "yad"

Title="壁紙変更"

#--------------------------------------------
# RtnSelectImage
#   $1 = 壁紙のファイル名 (例) ~/bg01.jpg
#--------------------------------------------
RtnSelectImage()
{
	_fn="$1"

	[ -z "${_fn}" ] && _fn="$HOME"

	_rtn=$(
		yad \
		--file \
		--filename="${_fn}" \
		--file-filter="画像 ファイル (*.jpg *.png *.gif) | *.jpg *.png *.gif" \
		--file-filter="すべてのファイル | *" \
		--add-preview --large-preview \
		--title="${Title}" \
		--width="640" \
		--on-top --center \
 		2>/dev/null \
 	)

	echo "${_rtn}"
}

readonly CbList="center|fill|scale|tile"

#----------------------------------
# RtnSelectBgStyle
#   $1 = 壁紙の配置方法 (例) fill
#----------------------------------
RtnSelectBgStyle()
{
	_1=""
	[ -n "$1" ] \
		&& _1="$1|${CbList}" \
		|| _1="${CbList}"

	_rtn=$(
		yad \
			--item-separator="|" \
			--separator="" \
			--form \
			--field="配置":CB "${_1}" \
			--title="${Title}" \
			--fixed \
			--on-top --center \
	 		2>/dev/null \
	)

	echo "${_rtn}"
}

#--------------
# RtnDialogYN
#--------------
RtnDialogYN()
{
	yad \
		--text "確定しますか ?" \
		--title="${Title}" \
		--fixed \
		--on-top --center \
 		2>/dev/null

	[ "$?" = "0" ] && echo "" || echo "1"
}

#-------
# main
#-------
ImageFile=""
BgStyle=""
Repeat=""

while true
do
	ImageFile=$(RtnSelectImage "${ImageFile}")
	[ -z "${ImageFile}" ] && break

	BgStyle=$(RtnSelectBgStyle "${BgStyle}")
	if [ -n "${BgStyle}" ]
	then
		feh --bg-${BgStyle} ${ImageFile}
		Repeat=$(RtnDialogYN)
		[ -z "${Repeat}" ] && break
	fi
done
