#!/bin/dash
# Ver.iwm20241108
#--------------------------------------------------------------------------------
# 使用例（"pv" "yad" をインストール）
#   dash: iwm_SubPkgInstall "pv" "yad"
#   ruby: %x(iwm_SubPkgInstall "pv" "yad")
#------------------------------------------------------------------------
Dpkg=$(dpkg -l)

# xterm をインストール
Installed=$(echo "${Dpkg}" | grep " xterm ")
if [ -z "${Installed}" ]
then
	sudo apt install xterm
fi

# パッケージをインストール
for _s1 in "${@}"
do
	Installed=$(echo "${Dpkg}" | grep " ${_s1} ")
	if [ -z "${Installed}" ]
	then
		$(
			xterm \
			-title "必要なパッケージをインストール" \
			-fa "Liberation Mono:size=11:antialias=true" \
			-e "sudo apt install ${_s1}; sleep 3;" \
		)
	fi
done
