#!/bin/dash
# Ver.iwm20241205
#--------------------------------------------------------------------------------
# デバイスを /media/$USER/以下 にマウント
#--------------------------------------------------------------------------------
readonly Bn=$(basename "$0")

# Tmp
readonly TmpFn="$HOME/${Bn}.tmp"
	echo "#!/bin/dash" > "${TmpFn}"

readonly Dev="/dev"
readonly Mnt="/media/$USER"

# "マウントされていない" "ntfs" "ext4" デバイス
lsblk --raw -o FSTYPE,MOUNTPOINTS,LABEL,NAME \
| sed -e "s/ /,/g" \
| grep -E "^(ext4|ntfs),," \
| while IFS="," read _FSTYPE _MOUNTPOINTS _LABEL _NAME
do
	##echo "${_FSTYPE},${_MOUNTPOINTS},${_LABEL},${_NAME}"
	_lbl=""
	if [ -z "${_LABEL}" ]
	then
		_lbl="${_NAME}"
	else
		_lbl="${_LABEL}"
	fi

	_dev="${Dev}/${_NAME}"
	_mnt="${Mnt}/${_lbl}"

	# Tmp
	echo "sudo mkdir -v ${_mnt} 2>/dev/null" >> "${TmpFn}"
	echo "sudo mount ${_dev} ${_mnt} 2>/dev/null" >> "${TmpFn}"
done

# 実行
##cat "${TmpFn}"
. "${TmpFn}"

rm "${TmpFn}"
