#!/bin/dash
# Ver.iwm20241212
#--------------------------------------------------------------------------------
# 使用例（"pv" "yad" をインストール）
#   dash: iwm_SubPkgInstall "pv" "yad"
#   ruby: %x(iwm_SubPkgInstall "pv" "yad")
#--------------------------------------------------------------------------------

# xterm をインストール
if [ ! -f "/usr/bin/xterm" ]
then
	sudo apt install xterm
fi

# パッケージのリスト取得
readonly Dpkg=$(LANG=C dpkg -l)

# パッケージをインストール
for _1 in "${@}"
do
	# ok: "^ii  ${_1} "
	# NG: '^ii  ${_1} '
	_2=$(echo "${Dpkg}" | grep -E "^ii  ${_1} ")
	if [ -z "${_2}" ]
	then
		xterm \
			-geometry "60x20" \
			-title "${_1} をインストール" \
			-fa "Liberation Mono:size=11:antialias=true" \
			-e "sudo apt install ${_1};"
	fi
done
