#!/bin/dash
# Ver.iwm20241109
#--------------------------------------------------------------------------------
# 使用例（"pv" "yad" をインストール）
#   dash: iwm_SubPkgInstall "pv" "yad"
#   ruby: %x(iwm_SubPkgInstall "pv" "yad")
#------------------------------------------------------------------------

# xterm をインストール
if [ ! -f "/usr/bin/xterm" ]
then
	sudo apt install xterm
fi

# パッケージのリスト取得
Dpkg=$(LANG=C dpkg -l)

# パッケージをインストール
for _s1 in "${@}"
do
	# ok: "^ii  ${_s1} "
	# NG: '^ii  ${_s1} '
	_s2=$(echo "${Dpkg}" | grep -E "^ii  ${_s1} ")
	if [ -z "${_s2}" ]
	then
		xterm \
			-geometry "60x20" \
			-title "${_s1} をインストール" \
			-fa "Liberation Mono:size=11:antialias=true" \
			-e "sudo apt install ${_s1};"
	fi
done
