#!/bin/dash
# Ver.iwm20250106
# 以下の使用を想定
#   Openbox + tint2
#   $HOME/.config/openbox/autostart から起動

# 複数起動禁止
readonly ThisPS=$(ps --no-headers -o pid,cmd -C $(basename "$0"))
[ $(echo "${ThisPS}" | wc -l) -ge 2 ] && exit

iwm_SubPkgInstall "yad"

readonly ObFile=$( \
cat <<-EOD
	rc.xml
	menu.xml
	autostart
EOD
)

ObArgv=""

IFS="
"
for _1 in $(echo "${ObFile}")
do
	ObArgv="${ObArgv} $HOME/.config/openbox/${_1}"
done

# Label ! Command ! Icon
readonly Menu=$( \
cat <<-EOD
	obconf ! obconf ! obconf
	openbox --restart ! openbox --restart ! gtk-refresh
	Edit Openbox ! mousepad ${ObArgv} ! mousepad
	tint2conf ! tint2conf ! tint2conf
	Conky On/Off ! iwm_conky_OnOff ! conky
	Wallpaper ! iwm_feh ! feh
EOD
)

# 変換後のフォーマット
# "Openbox!obconf!obconf|Openbox Restart!openbox --restart!gtk-refresh|tint2!tint2conf!tint2conf|Wallpaper!iwm_feh!feh|"
readonly MenuArgv=$( \
	echo "${Menu}" \
	| mawk \
	'$0 {
		sub(/^[[:blank:]]+/, "")
		sub(/[[:blank:]]+$/, "")
		gsub(/[[:blank:]]*\![[:blank:]]*/, "!")
		printf("%s|", $0)
	}'
)

# 通知エリアに常駐
yad --text="Openbox and other settings menus" \
	--notification --image="gtk-execute" \
	--command="iwm_openbox-shortcut-keys" \
	--menu="${MenuArgv}"
