#!/bin/dash
# Ver.iwm20241110

#----------------------------------------------------------------------
echo "\033[97;44m dpkg --purge \033[97;45m Name \033[0m"
echo

IFS=" "

dpkg -l \
| grep -E "^rm " \
| while read Desired Name Version
do
	echo "\033[97;45m ${Name} \033[0m"
	sudo dpkg --purge ${Name}
	echo
done

#----------------------------------------------------------------------
_s1=$(
cat <<-EOD
	dpkg --configure -a
	apt update
	apt upgrade
	apt dist-upgrade
	apt autoclean
	apt autoremove
EOD
)

IFS="
"

for _s2 in $(echo "${_s1}")
do
	echo "\033[97;44m ${_s2} \033[0m"
	# sudo
	eval "sudo ${_s2}"
	echo
done

#----------------------------------------------------------------------
Olist="${HOME}/$(basename "$0").list"

_s1=$(
cat <<-EOD
	dpkg -l | grep -E "^ii " > "${Olist}"
EOD
)

IFS="
"

for _s2 in $(echo "${_s1}")
do
	echo "\033[97;44m ${_s2} \033[0m"
	eval "${_s2}"
	echo
done

#----------------------------------------------------------------------
echo -n "(END)"
read _s1
