#!/bin/dash
# Ver.iwm20250113

# 消去
#   入力履歴
#   ファイル履歴
sudo find "$HOME" /root -name "*_history*" -or -name "recently-used.xbel*" | sudo xargs rm -rf

# ４世代以上のログを削除
readonly Gen="([4-9]|[1-9][0-9])"
sudo find /var/log | grep -E "\.${Gen}\.gz$|\.log\.${Gen}$" | sudo xargs rm -f

# Shutdown
systemctl poweroff
