#!/bin/dash
# Ver.iwm20241015

# (例) "Mono: Playback 46 [62%] [-28.00dB] [on]"
readonly MuteOn=$(amixer sget Master | grep ' \[on\]$')

if [ -z "${MuteOn}" ]
then
	amixer sset Master on
else
	amixer sset Master off
fi
