#!/bin/dash
# Ver.iwm20241229

# ALSA
#	[ $(amixer sget Master | grep -E ' \[on\]$')" ] \
#		&& amixer sset Master off \
#		|| amixer sset Master on

# PulseAudio
[ "$(LANG=C pactl get-sink-mute @DEFAULT_SINK@ | grep 'Mute: no')" ] \
	&& pactl set-sink-mute @DEFAULT_SINK@ 1 \
	|| pactl set-sink-mute @DEFAULT_SINK@ 0
