#!/bin/dash
# Ver.iwm20241108

iwm_SubPkgInstall "yad"

Title="Openbox ショートカットキー"

Text=$(cat <<EOD
<span face="sans" font-size="12pt" foreground="#f00">[音量]</span><span face="Monospace" font-size="11pt" foreground="#222">
  [Ctrl]+[F1]          <span foreground="#fa0">On/Off</span>
  [Ctrl]+[F2]          <span foreground="#f30">-2%</span>
  [Ctrl]+[F3]          <span foreground="#f30">+2%</span>
  [Ctrl]+[Shift]+[F2]  <span foreground="#fa0">-10%</span>
  [Ctrl]+[Shift]+[F3]  <span foreground="#fa0">+10%</span>
</span>
<span face="sans" font-size="12pt" foreground="#f00">[輝度]</span><span face="Monospace" font-size="11pt" foreground="#222">
  [Ctrl]+[F5]          <span foreground="#f30">-2%</span>
  [Ctrl]+[F6]          <span foreground="#f30">+2%</span>
  [Ctrl]+[Shift]+[F5]  <span foreground="#fa0">-10%</span>
  [Ctrl]+[Shift]+[F6]  <span foreground="#fa0">+10%</span>
</span>
EOD
)

$(
	yad \
	--title="${Title}" \
	--text="${Text}" \
	--button="gtk-close:0" \
	--width="300" \
	--fixed \
	--center \
	--on-top \
	2>/dev/null \
)
