#!/bin/dash
# Ver.iwm20250106
# デバイスをマウント／アンマウント

# 複数起動禁止
readonly ThisPS=$(ps --no-headers -o pid,cmd -C $(basename "$0"))
[ $(echo "${ThisPS}" | wc -l) -ge 2 ] && exit

iwm_SubPkgInstall "yad"

readonly TmpFn="./$$.tmp"

lsblk -n --raw -o FSTYPE,PATH,MOUNTPOINTS,LABEL,NAME \
| sed -e "s/ /,/g" \
| grep -v "^," \
| sort \
| while IFS="," read _FSTYPE _PATH _MOUNTPOINTS _LABEL _NAME
do
	if [ "${_MOUNTPOINTS}" != "/" ]
	then
		_lbl=""
		[ -n "${_LABEL}" ] \
			&& _lbl="${_LABEL}" \
			|| _lbl="${_NAME}"

		_mntp=""
		[ -n "${_MOUNTPOINTS}" ] \
			&& _mntp="TRUE" \
			|| _mntp="FALSE"

		echo "${_mntp},${_FSTYPE},${_NAME},${_lbl}" >> "${TmpFn}"
	fi
done

readonly TmpList=$(cat "${TmpFn}")
rm "${TmpFn}"

readonly Mnt="/media/$USER"
readonly Dev="/dev"

readonly List=$( \
	echo "${TmpList}" \
	| sed -e "s/,/\\n/g" \
	| yad --list \
		--checklist \
		--column="" --column="FS" --column="${Dev}" --column="${Mnt}" \
		--print-all --separator="," \
		--button="Cancel:1" --button="OK:0" \
		--title="デバイスのマウント" \
		--height="320" --width="480" --fixed --borders="4" --center --on-top \
		2>/dev/null \
)

if [ -z "${List}" ] || [ "${List}" = "${TmpList}" ]
then
	exit
fi

pkexec echo "${List}" \
| while IFS="," read _Chk _2 _Dev _Mnt
do
	_Mnt="${Mnt}/${_Mnt}"
	_Dev="${Dev}/${_Dev}"

	if [ "${_Chk}" = "TRUE" ]
	then
		##echo "mkdir -v ${_Mnt}"
		sudo mkdir -v ${_Mnt} 2>/dev/null
		##echo "mount ${_Dev} ${_Mnt}"
		sudo mount ${_Dev} ${_Mnt} 2>/dev/null
	else
		##echo "umount ${_Dev}"
		sudo umount ${_Dev} 2>/dev/null
	fi
done
