#!/bin/dash
# Ver.iwm20241212

ls -lah -tr --time-style=+'%Y/%m/%d %H:%M:%S' $* \
| grep -e '^-' \
| while IFS=" " read _1 _2 _3 _4 _5 _6 _7 _8
do
	echo "\033[37m${_1} ${_3} ${_4} \033[93m${_6} ${_7} \033[92m${_8}\033[0m"
done
